yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_filure'
handler500 = 'core.views.internal_server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts_app')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .constants import TEXT_LEN


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название',
        help_text='Название группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Адрес страницы',
        help_text='Адрес страницы группы'
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Описание группы'
    )

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        blank=False,
        verbose_name='Текст',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='День, когда был опубликован пост'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой относится пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text[:TEXT_LEN]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Пост',
        help_text='Пост, к которому будет оставлен комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Автор комментария'
    )
    text = models.TextField(
        blank=False,
        verbose_name='Текст',
        help_text='Текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария',
        help_text='День, когда был опубликован комментарий'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self) -> str:
        return self.text[:TEXT_LEN]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.urls import reverse
from utils import paginate_page
from .models import Group, Post, User, Comment, Follow
from .constants import PER_PAGE
from .forms import PostForm, CommentForm


def index(request):
    post_list = Post.objects.select_related('group', 'author').all()
    page_obj = paginate_page(request, post_list)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginate_page(request, post_list)
    template = 'posts/group_list.html'
    posts = group.posts.all()[:PER_PAGE]
    context = {'group': group,
               'posts': posts,
               'page_obj': page_obj
               }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = User.objects.filter(username=username).first()
    posts = author.posts.all()
    page_obj = paginate_page(request, posts)
    user = request.user
    author = User.objects.get(username=username)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=user, author=author).exists()
    context = {'author': author,
               'page_obj': page_obj,
               'following': following
               }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post_id=post_id)
    context = {'post': post,
               'form': form,
               'comments': comments,
               }
    return render(request, template, context)


@login_required
def post_create(request):
    groups = Group.objects.all()
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    context = {'form': form,
               'groups': groups
               }

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    else:
        return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    groups = Group.objects.all()

    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post.id)
    else:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id=post.id)

    context = {'form': form,
               'groups': groups,
               'post': post,
               'is_edit': True
               }

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'includes/comments.html', {'form': form,
                  'post': post})


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate_page(request, posts)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context=context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author).exists()
    if user != author and not is_follower:
        Follow.objects.create(user=user, author=author)

    return redirect(reverse('posts:profile',
                    kwargs={'username': author.username}))


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author).exists()
    if user != author and is_follower:
        Follow.objects.filter(user=user, author=author).delete()

    return redirect(reverse('posts:profile',
                    kwargs={'username': author.username}))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
    {% if is_edit %}
        Редактировать запись
    {% else %}
        Новый пост
    {% endif %}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                    Редактировать запись
                {% else %}
                    Новый пост
                {% endif %}            
              </div>
              <div class="card-body">        
                <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                </div class="form-error"{{ form.non_field_errors }}>
                {% for f in form %}
                <div class="form-group row my-3 p-3"><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}   
                    <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
    Страница подписок
{% endblock %}
{% block content %}
    <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        <article>
        {% include 'posts/includes/switcher.html' %}
        {% cache 20 follow_page %}
        {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
            {% if post.group %}  
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% endcache %}
        {% include 'posts/includes/paginator.html' %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Здесь будет информация о группах проекта Yatube
{% endblock %}
{% block content %}
    <div class="container py-5">
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in posts %}
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}  
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
    Это главная страница проекта Yatube
{% endblock %}
{% block content %}
    <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        {% include 'posts/includes/switcher.html' %}
        {% cache 20 index_page %}
        {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}  
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
        {% endcache %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Пост {{ post.text|truncatechars:30}}
{% endblock%}
{% block content %}
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif%}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="ard-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a> 
          {% endif %}
        </article>
      </div>
      {% include  'posts/includes/comments.html' %}
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
      <div class="container py-5 mb-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ post.author.posts.count }} </h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light mb-5"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary mb-5"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
        {% for post in page_obj %}   
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}  
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}              
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}  
      </div>
{% endblock %}